# Generated by Django 5.1.3 on 2024-11-14 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('fav', models.BooleanField(default=False)),
                ('createdate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
