# Generated by Django 5.1.3 on 2024-11-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='auther',
        ),
    ]
