# Generated by Django 5.1.3 on 2024-11-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0003_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='discription',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='fav',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='createdate',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='store_name',
        ),
        migrations.AddField(
            model_name='book',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
